### PR TITLE
 Add support for Azure, OpenAI, Llama2, Palm, Cohere, Replicate Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/

Here's a sample of how it's used:

```
from litellm import completion, acompletion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# llama2 call
model_name = "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1"
response = completion(model_name, messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@olegklimov @mitya52 can I get a review on this PR ?😊

If the initial commit looks good happy to add more docs/tests too

**Comment by olegklimov** [comment]
interesting

**Comment by sammcj** [comment]
This is really neat - I didn't realise how powerful that library is!

**Comment by ishaan-jaff** [comment]
Hi @olegklimov @sammcj any update on this ?

**Comment by sammcj** [comment]
@ishaan-jaff it needs a maintainer to review it.

**Review by sammcj — APPROVED** [review]

**Comment by olegklimov** [comment]
It's an actually interesting change. We'll look at it next week or so. Sorry if it's slow, we really really want to get the stable version out this week.

**Comment by ishaan-jaff** [comment]
no worries let me know if i can help with anything

**Comment by mitya52** [comment]
we integrated litellm to server, now it works with OpenAI and Anthropic chat models

**Pull request closed without merging**
