### PR TITLE
Settings tab UI/UX improvements

### PR DESCRIPTION
**Pull request by valaises**
Changelist:
* API Keys tab link on "Model Hosting Tab" is clickable and leads to the tab-settings
* API Keys in the tab-settings are now partially masked with "*" 
* Added toast pop-up on save event for input field of Integration in the tab-settings
* Removed btn that saves Integrations in the tab-settings. Save event is applied to blur event of an input field

### CODE REVIEW

**Comment by olegklimov** [comment]
> API Keys tab link
Works

> API Keys in the tab-settings are now partially masked with *
Good idea

> pop-up
Good idea as well

> that saves Integrations
The direction is right, but I'd rather have "Edit" and "Save" as buttons. Edit changes "***" to letters, "Save" saves and opens the popup when it sees it's saved.

**Comment by hazratisulton** [comment]
Empty field with text "undefined" - FIXED 
image

Instead of short text displayed undifined - FIXED 
image

saved even if no changes in empty field - FIXED

olegklimov's comment "but I'd rather have "Edit" and "Save" as buttons. Edit changes "***" to letters, "Save" saves and opens the popup when it sees it's saved" not implemented

**Review by hazratisulton — APPROVED** [review]

**Comment by valaises** [comment]
@olegklimov waiting for your review

**Review by olegklimov — APPROVED** [review]

**Comment by olegklimov** [comment]
merged manually

**Pull request closed without merging**
